config/routes.rb
Rails.application.routes.draw do
  resources :xclones do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/xclone.rb
class Xclone < ApplicationRecord
  attribute :content, :string
  validates :content, length: {in: 1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/controllers/xclones_controller.rb
class XclonesController < ApplicationController
  before_action :set_xclone, only: [:show, :edit, :update, :destroy]

  def index
    @xclones = Xclone.all
  end

  def new
    @xclone = Xclone.new
  end

  def create
    @xclone = Xclone.new(xclone_params)
    if params[:back]
      render :new
    else
      if @xclone.save
        redirect_to xclones_path, notice: "投稿しました！"
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def show
    @xclone = Xclone.find(params[:id])
  end

  def edit
    @xclone = Xclone.find(params[:id])
  end

  def update
    @xclone = Xclone.find(params[:id])
    if @xclone.update(xclone_params)
      redirect_to xclones_path, notice: "投稿内容を編集しました！"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @xclone.destroy
    redirect_to xclones_path, notice:"投稿を削除しました！"
  end

  def confirm
    @xclone = Xclone.new(xclone_params)
    render :new if @xclone.invalid?
  end


  private

  def xclone_params
    params.require(:xclone).permit(:content)
  end

  def set_xclone
    @xclone = Xclone.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/xclones_helper.rb
module XclonesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_xclones_path
    elsif action_name == 'edit'
      xclone_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bigtask2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tops", "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= image_tag("Xclone.jpg", width: "100%", height: "300") %>
    <%= yield %>
  </body>
</html>

app/views/xclones/_form.html.erb
<%= form_with(model: @xclone, local: true, url: choose_new_or_edit, data: {turbo: false}) do |form| %>
  <% if @xclone.errors.any? %>
    <div id="error_explanation">
      <h2><%= @xclone.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @xclone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="xclone_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "投稿一覧画面にもどる", xclones_path %>

app/views/xclones/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @xclone, local: true, data: {turbo: false}) do |form| %>
  <%= form.hidden_field :content %>

  <p>本文:<%= @xclone.content %></p>
  <%= form.submit  "投稿する" %>

  <%= form.submit "戻る", name: 'back' %>

<% end %>

app/views/xclones/edit.html.erb
<h2>投稿内容を編集する</h2>

<%= render 'form' %>

app/views/xclones/index.html.erb
<div class="container">
  <h1 class="title">投稿一覧</h1>

  <p><%= notice %></p>

  <table>
    <tr>
      <th class="content">内容</th>
    </tr>

    <% @xclones.each do |xclone| %>
      <tr>
        <td class="contents"><%= xclone.content %></td>
      </tr>

      <tr>
        <td><%= link_to "詳細を確認する", xclone_path(xclone.id) %></td>
        <td><%= link_to "投稿内容を編集する", edit_xclone_path(xclone.id), data: { turbo_method: 'get', turbo_confirm: '本当に編集していいですか？' } %></td>
        <td><%= link_to "投稿を削除する", xclone_path(xclone.id), data: { turbo_method: :delete, turbo_confirm: '本当に削除していいですか？' } %></td>
      </tr>
    <% end %>
  </table>

  <%= link_to '新しく投稿する',new_xclone_path %>
</div>

app/views/xclones/new.html.erb
<h2>投稿する</h2>

<%= render 'form' %>

app/views/xclones/show.html.erb
<h1>投稿詳細画面</h1>
<p>内容: <%= @xclone.content %></p>